### ISSUE TITLE
native bindings

### ISSUE THREAD

**Issue by ralphtheninja** [ralphtheninja/pgdown#3]
https://github.com/brianc/node-postgres#native-bindings

having issues on linux:

```
$ npm i pg-native -S
-
> libpq@1.8.0 install /home/lms/src/Level/postgresdown/node_modules/pg-native/node_modules/libpq
> node-gyp rebuild

find: `/usr/pg*': No such file or directory
gyp: Call to 'which pg_config || find /usr/bin /usr/local/bin /usr/pg* /opt -executable -name pg
_config -print -quit' returned exit status 1. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-g
yp/lib/configure.js:355:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.2.0-27-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bi
n/node-gyp.js" "rebuild"
gyp ERR! cwd /home/lms/src/Level/postgresdown/node_modules/pg-native/node_modules/libpq
gyp ERR! node -v v4.3.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm ERR! Linux 4.2.0-27-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "pg-native" "-S"
npm ERR! node v4.3.1
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE

npm ERR! libpq@1.8.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the libpq@1.8.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the libpq package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls libpq
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/lms/src/Level/postgresdown/npm-debug.log
```

**Comment by ralphtheninja** [comment]
Apparently we can't use `pg-native` yet because it doesn't have support for cursors. It would also be nice to have prebuilt binaries to ease the installation process, see https://github.com/brianc/node-pg-native/issues/39

**Comment by deanlandolt** [comment]
FWIW I've got a plan to move away from cursors completely -- pg's really stingy w/ its db connections, and cursors eat one, or force you to do some otherwise expensive stuff if you take the `WITH HOLD` approach. This ought to allow us to move to pg-native at some point.
